apiVersion: apps/v1
kind: Deployment
metadata:
  name: geradordesenha
spec:
  selector:
    matchLabels:
      app: geradordesenha
  template:
    metadata:
      labels:
        app: geradordesenha
    spec:
      containers:
      - name: geradordesenha
        image: viniciuscaol/geradordesenha:v{{TAG}}
        ports:
        - containerPort: 80